name: Build

on:
 push:
  branches:
  - 'devUnofficial'
  - 'github-action'
  paths:
  - '.github/workflows/build.yml'
  - 'action.yml'
  - 'sfall/**'

jobs:
 Build:
  name:    sfall
  runs-on: windows-latest
  steps:

  - name: Clone sfall
    uses: actions/checkout@v2

  # Action is used twice for self-testing only

  - name: ReleaseXP build
    id:   build
    uses: ./
    with:
     release-xp: true

  - name: DevXP build
    id:   build2
    uses: ./
    with:
     dev-xp: true

  - name:  Prepare artifact
    run:   |
           :
           mkdir -p ddraw/DevXP
           if [[ "${{ steps.build2.outputs.dev-xp }}" != "" ]]; then
              cp "${{ steps.build2.outputs.dev-xp }}"     ddraw/DevXP
              cp "${{ steps.build2.outputs.dev-xp-pdb }}" ddraw/DevXP
           fi

           if [[ "${{ steps.build.outputs.release-xp }}" != "" ]]; then
              cp "${{ steps.build.outputs.release-xp }}"  ddraw
           fi
    shell: bash

  - name: Upload artifacts
    uses: actions/upload-artifact@v2
    with:
     name:           sfall-ext
     path:           ddraw
     retention-days: 7
